### ISSUE TITLE
什么时候能再有测试资格啊呜呜

### ISSUE THREAD

**Issue by pompousdwj** [pcccccc/SimpleLiveTVOS#10]

**Comment by pcccccc** [comment]
电报群每天都会放

**Comment by pompousdwj** [comment]
请问怎么才能加群



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: PangChong ***@***.***&gt;
发送时间: 2024年6月28日 14:01
收件人: pcccccc/SimpleLiveTVOS ***@***.***&gt;
抄送: pompousdwj ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [pcccccc/SimpleLiveTVOS] 什么时候能再有测试资格啊呜呜 (Issue #10)





 
电报群每天都会放

**Comment by pcccccc** [comment]
不就在项目介绍里面吗？随便加。
