### ISSUE TITLE
关于返回键的建议

### ISSUE THREAD

**Issue by univeous** [pcccccc/SimpleLiveTVOS#13]
在其他软件（比如cheers）中，暂停/刷新等控制按钮出现时按下返回键会隐藏按钮，再按一次才会退出播放；而此项目中即使按钮出现按下返回也会退出播放。
希望改进一下，添加配置项，或是让按钮消失更快一点。

另外能否在从其他应用切换回来时执行一次自动刷新？

**Comment by pcccccc** [comment]
之前有，1.2.0改版的时候给忘掉了。

下次更新修复。

**Comment by pcccccc** [comment]
`另外能否在从其他应用切换回来时执行一次自动刷新？`
这一条估计不行，需要手动刷新
