### ISSUE TITLE
老哥,能不能上清晰度选项?我感觉好像不是按照最高清的在播放

### ISSUE THREAD

**Issue by birdmichael** [pcccccc/SimpleLiveTVOS#2]

**Comment by pcccccc** [comment]
清晰度切换在做。
你觉得不高清的平台如果是B站，需要去设置里面扫码登录B站，才能获取清晰度更高的直播。
另外扫码提示成功外面提示未登录的问题，是个显示bug，只要内页提示成功就可以了。

**Comment by birdmichael** [comment]
ok
是虎牙.感觉不是很清晰

**Comment by birdmichael** [comment]
再推一个feature吧..
频道下,本地存一个观看历史...
代替了 各端的 收藏
这个也简单

**Comment by pcccccc** [comment]
> ok 是虎牙.感觉不是很清晰

虎牙没有任何人反馈过不清晰，你拍个图片看看

**Comment by pcccccc** [comment]
> 再推一个功能吧.. 频道下，本地存一个观看历史... 代替了各端的 这个收藏也简单

Apple TV 的缓存空间很宝贵，我不是很希望用来保存历史。

可能会开发一个保存近10条/20条观看历史的功能。

**Comment by birdmichael** [comment]
0 0 这种数据
你存几百条历史。也占不到10k吧

需要根据平台的最近观看哦

**Comment by pcccccc** [comment]
> 0 0 这种数据 你存几百条历史。也占不到10k吧
> 
> 需要根据平台的最近观看哦

看怎么存，而且更新数据和状态很麻烦。

**Comment by pcccccc** [comment]
1.1.0 已经完成
