### ISSUE TITLE
抖音直播是否考虑增加蓝光的清晰度选项

### ISSUE THREAD

**Issue by knightyui** [pcccccc/SimpleLiveTVOS#5]
最近抖音放开了LOL直播，发现有的直播间在手机上看的时候，有蓝光的清晰度选项，但是atv上没有，最高只有超清，画面不可避免的会出现模糊的情况，是否考虑增加清晰度选项

**Comment by pcccccc** [comment]
刚看了一下，可以添加，晚上弄一下。

**Comment by pcccccc** [comment]
已更新

**Comment by knightyui** [comment]
大佬牛的，啥时候上apple store了必须支持一波
