### ISSUE TITLE
看虎牙的直播有弹幕没画面和声音

### ISSUE THREAD

**Issue by Gokotx** [pcccccc/SimpleLiveTVOS#6]
- 情况 1：打开虎牙的任一直播内容，直播没有画面和声音，但是弹幕正常。
- 情况 2：打开虎牙的任一直播内容，有画面和声音，但是几秒钟后画面和声音直接停止卡主（问题应该同上）。
ps：其他直播平台的可以正常播放
系统：tvOS 17.3

![Screenshot 2024-03-04 at 16 01 57](https://github.com/pcccccc/SimpleLiveTVOS/assets/34123995/6c443e5b-032a-48c5-bcfb-b2d8483bf2dc)

**Comment by Gokotx** [comment]
不好意思，刚看到这边上周刚提交了修复 huya 卡死的代码，我更新下试试。

**Comment by pcccccc** [comment]
> 不好意思，刚看到这边上周刚提交了修复 huya 卡死的代码，我更新下试试。

OK，你更新一下，如果还不行，就把房间号告诉我。

**Comment by Gokotx** [comment]
好评！可以了，用了最新的代码就可以了～
（但是有一个点是不是可以考虑优化下，就是在播放页面返回后，页面已经退到首页了，但是直播的声音还在继续播放 1-2s 才结束。）

**Comment by pcccccc** [comment]
> 好评！可以了，用了最新的代码就可以了～ （但是有一个点是不是可以考虑优化下，就是在播放页面返回后，页面已经退到首页了，但是直播的声音还在继续播放 1-2s 才结束。用其他视频类App 没这个问题。）

OK，晚点看下。

**Comment by Gokotx** [comment]
tv 4k （当前最新款，应该不是设备性能问题），需要我提供什么测试信息给你不

**Comment by pcccccc** [comment]
你使用debug模式跑的吗？Testflight上面的有没有问题

**Comment by Gokotx** [comment]
是的，但是我刚才试了下 Testflight 上的也是一样的问题。
是不是因为我连了 Homepod 的原因（看起来这个问题像早期 Mac 连 Homepod 时，视频音频延迟的问题。）

**Comment by Gokotx** [comment]
但是同样的我都是连的 Homepod，其他视频类 App 没这个问题，包括我装的 B 站的那个也没问题。

**Comment by pcccccc** [comment]
有可能，因为播放器SDK的原因。因为直播有一些FLV源，所以只能选择使用第三方的播放器。
如果你会写代码的话可以简单测试一下，分别使用系统的AVPlayer还有程序中引用的KSPlayer测试效果。

**Comment by Gokotx** [comment]
大概率是这个问题。看了https://github.com/yichengchen/ATV-Bilibili-demo 这个项目的播放，就是用的 AVPlayer ，然后没有问题。
你如果没有接 Homepod 的话，你可以尝试在 Apple TV中把音频输出修改成通过 Mac的扬声器，一样也可以复现这个问题。
（代码已经好多年没写了，可能改不动，勉强看看还行，哈哈哈。）

**Comment by pcccccc** [comment]
这个问题我这边暂时应该是解决不了，我报告给KSPlayer的作者吧，看他什么时候解决的话我跟进一下。

**Comment by pcccccc** [comment]
[https://github.com/kingslay/KSPlayer/issues/362](url)

**Comment by Gokotx** [comment]
好的～ 影响也不是特别大。只在退出页面是有一会儿声音。忍一下，哈哈哈
