### ISSUE TITLE
期望弹幕字体大小可以更多选项

### ISSUE THREAD

**Issue by samDDD123** [pcccccc/SimpleLiveTVOS#7]
目前弹幕字体只有三个选项，小字体就太小了，其他又有些大，可否增加多个字体大小选择？非常感谢

**Comment by pcccccc** [comment]
好，下版本添加

**Comment by pcccccc** [comment]
<img width="669" alt="image" src="https://github.com/pcccccc/SimpleLiveTVOS/assets/13974510/793e36ae-428d-464f-89a1-79c7d2ab7838">

打算改成这种，怎么样？

最早的版本是直接输入的，群里的朋友们觉得直接输入比较难用。

这种可能更灵活一些，上部分进行设置后，下面可以比较直观的看到弹幕字体大小。
